openapi: 3.0.1
info:
  title: Swagger Home-Banking
  description: 'This is Home-Banking Server'
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://admin.swagger.io/v2
- url: http://admin.swagger.io/v2
tags:
- name: Address
  description: Everything about your Address
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /address/{addressId}:
    get:  
      tags:
      - Address
      summary: Find Address by ID
      description: Returns a single Address Entity
      operationId: getById
      parameters:
      - name: addressId
        in: path
        description: ID of the Address to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/address'
            application/json:
              schema:
                $ref: '#/components/schemas/address'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Current account not found
          content: {}
      security:
      - api_key: []
  /currentaccount:
    get:  
      tags:
      - Address
      summary: Find all the Address
      description: Returns all the Addresses
      operationId: getAll
      #parameters:
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/address'
            application/json:
              schema:
                $ref: '#/components/schemas/address'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: current acconunts not found
          content: {}
      security:
      - api_key: []        
    post:
      tags:
      - Address
      summary: Adds an address
      operationId: addAddress
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  #type: double
                  description: added current account
      responses:
        405:
          description: Invalid input
          content: {}
      security:
      - admin_auth:
        - write:users
        - read:users
      x-codegen-request-body-name: body            
  #/currentaccount:
    delete:
      tags:
      - Address
      summary: Deletes an Address
      operationId: delete
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: user not found
          content: {}
      security:
      - admin_auth:
        - write:users
        - read:users

components:
  schemas:
    address:
      required:
      - id
      - via
      - civico
      - comune
      - provincia
      - regione
      - stato
      - cap 
      - user_id
      type: object
      properties:
        id:
          type: integer
          format: int64
        via:
          type: string
        civico:
          type: string
        comune:
          type: string
        provincia:
          type: string
        regione:
          type: string
        stato:
          type: string
        cap:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64          
      xml:
        name: Address
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  securitySchemes:
    admin_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://admin.swagger.io/oauth/dialog
          scopes:
            write:users: modify current Accounts in your account
            read:users: read your current Accounts
    api_key:
      type: apiKey
      name: api_key
      in: header