openapi: 3.0.1
info:
  title: Swagger Home-Banking
  description: 'This is Home-Banking Server'
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://admin.swagger.io/v2
- url: http://admin.swagger.io/v2
tags:
- name: Account
  description: Everything about your Account
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /bank/{accountId}:
    get:  
      tags:
      - Account
      summary: Find Account by ID
      description: Returns a single Account Entity
      operationId: getById
      parameters:
      - name: accountId
        in: path
        description: ID of the Account to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/account'
            application/json:
              schema:
                $ref: '#/components/schemas/account'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Current account not found
          content: {}
      security:
      - api_key: []
  /account:
    get:  
      tags:
      - Account
      summary: Find all the acconunts
      description: Returns all the acconunts
      operationId: getAll
      #parameters:
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/account'
            application/json:
              schema:
                $ref: '#/components/schemas/account'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: current acconunts not found
          content: {}
      security:
      - api_key: []        
    post:
      tags:
      - Account
      summary: Adds an Account
      operationId: addAccount
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  #type: double
                  description: added Account
      responses:
        405:
          description: Invalid input
          content: {}
      security:
      - admin_auth:
        - write:users
        - read:users
      x-codegen-request-body-name: body       
  #/currentaccount:
    delete:
      tags:
      - Account
      summary: Deletes an Account
      operationId: delete
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description:  Bank not found
          content: {}
      security:
      - admin_auth:
        - write:users
        - read:users
components:
  schemas:
    account:
      required:
      - id
      - date_of_creation
      - user_id
      type: object
      properties:
        id:
          type: integer
          format: int64
        date_of_creation:
          type: string
        user_id:
          type: integer
          format: int64
      xml:
        name: account
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  securitySchemes:
    admin_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://admin.swagger.io/oauth/dialog
          scopes:
            write:users: modify Bank in your account
            read:users: read your Bank
    api_key:
      type: apiKey
      name: api_key
      in: header