openapi: 3.0.1
info:
  title: Swagger admin
  description: 'This is a sample server admin server.  You can find out more about     Swagger
    at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For
    this sample, you can use the api key `special-key` to test the authorization     filters.'
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://admin.swagger.io/v2
- url: http://admin.swagger.io/v2
tags:
- name: Bank
  description: Everything about your Bank
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /bank/{bankId}:
    get:  
      tags:
      - Bank
      summary: Find Bank by ID
      description: Returns a single Bank Entity
      operationId: getById
      parameters:
      - name: bankId
        in: path
        description: ID of the Bank to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/bank'
            application/json:
              schema:
                $ref: '#/components/schemas/bank'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Current account not found
          content: {}
      security:
      - api_key: []
  /bank:
    get:  
      tags:
      - Bank
      summary: Find all the banks
      description: Returns all the banks
      operationId: getAll
      #parameters:
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/bank'
            application/json:
              schema:
                $ref: '#/components/schemas/bank'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: current acconunts not found
          content: {}
      security:
      - api_key: []        
    post:
      tags:
      - Bank
      summary: Adds a Bank
      operationId: addBank
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  #type: double
                  description: added Bank
      responses:
        405:
          description: Invalid input
          content: {}
      security:
      - admin_auth:
        - write:users
        - read:users
      x-codegen-request-body-name: body            
  #/currentaccount:
    delete:
      tags:
      - Bank
      summary: Deletes a Bank
      operationId: delete
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description:  Bank not found
          content: {}
      security:
      - admin_auth:
        - write:users
        - read:users
components:
  schemas:
    bank:
      required:
      - id
      - name
      - filiale_description
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        filiale_description:
          type: string
      xml:
        name: bank
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  securitySchemes:
    admin_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://admin.swagger.io/oauth/dialog
          scopes:
            write:users: modify Bank in your account
            read:users: read your Bank
    api_key:
      type: apiKey
      name: api_key
      in: header