openapi: 3.0.1
info:
  title: Swagger Home-Banking
  description: 'This is Home-Banking Server'
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://admin.swagger.io/v2
- url: http://admin.swagger.io/v2
tags:
- name: currentAccount
  description: Everything about your current Account
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /currentaccount/id/{currentaccountId}:
    get:  
      tags:
      - Current account
      summary: Find Current Account by ID
      description: Returns a single Current account
      operationId: getById
      parameters:
      - name: currentaccountId
        in: path
        description: ID of current account to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/currentAccount'
            application/json:
              schema:
                $ref: '#/components/schemas/currentAccount'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Current account not found
          content: {}
      security:
      - api_key: []
  /currentaccount/iban/{iban}:
    get:  
      tags:
      - Current Account
      summary: Find Current account by Iban
      description: Returns a single Current Account
      operationId: getByIban
      parameters:
      - name: iban
        #type: string
        in: path
        description: ID of current account to return
        required: true
        schema:
          type: string
          #format: int64
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/currentAccount'
            application/json:
              schema:
                $ref: '#/components/schemas/currentAccount'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Current Account not found
          content: {}
      security:
      - api_key: []
  /currentaccount/:
    get:  
      tags:
      - Current Accounts
      summary: Find all the Current Accounts
      description: Returns all the current Accounts
      operationId: getAll
      #parameters:
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/currentAccount'
            application/json:
              schema:
                $ref: '#/components/schemas/currentAccount'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: current acconunts not found
          content: {}
      security:
      - api_key: []        
    post:
      tags:
      - current Accont
      summary: Add a current account
      operationId: addCurrentAccount
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  #type: double
                  description: added current account
      responses:
        405:
          description: Invalid input
          content: {}
      security:
      - admin_auth:
        - write:users
        - read:users
      x-codegen-request-body-name: body            
  #/currentaccount:
    put:
      tags:
      - currentAccount
      summary: Update an existing current account
      operationId: updateCurrentAccount
      requestBody:
        description: currentAccount object that needs to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/currentAccount'
          application/xml:
            schema:
              $ref: '#/components/schemas/currentAccount'
        required: true
      responses:
        400:
          description: Invalid parameters supplied
          content: {}
        404:
          description: Current Account not found
          content: {}
        405:
          description: Validation exception
          content: {}
      security:
      - admin_auth:
        - write:users
        - read:users
      x-codegen-request-body-name: body
  #/currentaccount:
    delete:
      tags:
      - currentAccount
      summary: Deletes a current account
      operationId: deleteCurrentAccount
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: user not found
          content: {}
      security:
      - admin_auth:
        - write:users
        - read:users

components:
  schemas:
    currentAccount:
      required:
      - id
      - iban
      - balance
      - account_id
      type: object
      properties:
        id:
          type: integer
          format: int64
        iban:
          type: string
        balance:
          type: number
          example: mitnik
        account_id:
          type: integer
          format: int64
      xml:
        name: currentAccount
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  securitySchemes:
    admin_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://admin.swagger.io/oauth/dialog
          scopes:
            write:users: modify current Accounts in your account
            read:users: read your current Accounts
    api_key:
      type: apiKey
      name: api_key
      in: header