openapi: 3.0.1
info:
  title: Swagger admin
  description: 'This is a sample server admin server.  You can find out more about     Swagger
    at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For
    this sample, you can use the api key `special-key` to test the authorization     filters.'
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://admin.swagger.io/v2
- url: http://admin.swagger.io/v2
tags:
- name: Prestito
  description: Everything about your Prestito
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /prestito/{accountId}:
    get:  
      tags:
      - Prestito
      summary: Find Prestito by ID
      description: Returns a single Account Entity
      operationId: getByAccountId
      parameters:
      - name: accountId
        in: path
        description: ID of the Account to return related Prestito
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/prestito'
            application/json:
              schema:
                $ref: '#/components/schemas/prestito'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Prestito not found
          content: {}
      security:
      - api_key: []
  /prestito:
    get:  
      tags:
      - Prestito
      summary: Find all the prestiti
      description: Returns all the prestiti
      operationId: getAll
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/prestito'
            application/json:
              schema:
                $ref: '#/components/schemas/prestito'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Prestito not found
          content: {}
      security:
      - api_key: []
  #/prestito          
    post:
      tags:
      - Prestito
      summary: Adds a Prestito
      operationId: insert
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  #type: double
                  description: added Prestito
      responses:
        405:
          description: Invalid input
          content: {}
        409:
          description: Prestito gia presente nel DB  
      security:
      - admin_auth:
        - write:users
        - read:users
      x-codegen-request-body-name: body       
    #/prestito
    put:
      tags:
      - Prestito
      summary: Update an existing Prestito
      operationId: update
      requestBody:
        description: Prestito object that needs to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/prestito'
          application/xml:
            schema:
              $ref: '#/components/schemas/prestito'
        required: true
      responses:
        400:
          description: Invalid parameters supplied
          content: {}
        404:
          description: Il Prestito non presente nel DB
          content: {}
        405:
          description: Validation exception
          content: {}
      security:
      - admin_auth:
        - write:users
        - read:users
      x-codegen-request-body-name: body
    #/prestito    
    delete:
      tags:
      - Prestito
      summary: Deletes a Prestito
      operationId: delete
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description:  Il Prestito non presente ne DB
          content: {}
      security:
      - admin_auth:
        - write:users
        - read:users
components:
  schemas:
    prestito:
      required:
      - id
      - import
      - interest
      - account_id
      - numero_rata
      - importo_rata
      - durata
      - numero_rata_mancanti
      - prestito_type
      type: object
      properties:
        id:
          type: integer
          format: int64
        import:
          type: number
        interest:
          type: number
        account_id:
          type: integer
          format: int64
        numero_rata:
          type: integer
          format: int64
        importo_rata:
          type: number
        durata:
          type: string
        numero_rata_mancanti:
          type: integer
          format: int64
        prestito_type:
          type: string        
      xml:
        name: prestito
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  securitySchemes:
    admin_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://admin.swagger.io/oauth/dialog
          scopes:
            write:users: modify Bank in your account
            read:users: read your Bank
    api_key:
      type: apiKey
      name: api_key
      in: header